version: 2
run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120

formatters-settings:
  goimports:
    local-prefixes: github.com/yafeng-Soong/kizaru

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
